# name: Dashboard Pipeline

# on:

#   schedule:
#     - cron: '*/5 * * * *'  # toutes les 5 minutes

#   workflow_dispatch:


# permissions:
#   contents: write


# jobs:

#   pipeline:

#     runs-on: ubuntu-latest

#     timeout-minutes: 30


#     steps:

#       - name: Cloner repo
#         uses: actions/checkout@v4


#       - name: Installer Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.11'


#       - name: Installer dépendances
#         run: |
#           pip install -r requirements.txt
#           pip install openpyxl


#       - name: Exécuter pipeline
#         run: |
#           python scripts/pipeline.py


#       - name: Commit et push des données
#         run: |
#           git config --global user.name "github-actions"
#           git config --global user.email "github-actions@github.com"

#           git add .

#           git commit -m "update data every 5 minutes" || echo "No changes"

#           git push